version: 2.1
jobs:
  build_and_test:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run:
          name: Run tests, reporting code coverage
          command: |
            apk add git
            mix coveralls.circle
      - run: mix credo

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test:
          context: bank_validator_br
          matrix:
            parameters:
              image:
                - hexpm/elixir:1.7.4-erlang-19.3.6.13-alpine-3.12.0
                - hexpm/elixir:1.8.2-erlang-20.3.8.26-alpine-3.12.0
                - hexpm/elixir:1.9.4-erlang-20.3.8.26-alpine-3.12.0
                - hexpm/elixir:1.10.4-erlang-21.3.8.17-alpine-3.12.0
                - hexpm/elixir:1.10.4-erlang-23.0.3-alpine-3.12.0
