version: 2.1
jobs:
  build_and_test:
    docker:
      - image: hexpm/elixir:1.8.2-erlang-22.3.4.10-alpine-3.12.0
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix test
      - run: mix credo
      - run:
          command: mix coveralls.github
          environment:
            GITHUB_TOKEN: ${GITHUB_TOKEN}

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test:
          context: bank_validator_br
