version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/elixir:1.8
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
      - run: mix credo
      - run:
          command: mix coveralls.github
          environment:
            GITHUB_TOKEN: ${GITHUB_TOKEN}

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test:
          context: bank_validator_br
